### PR TITLE
Implements sqrt from math module

### PR DESCRIPTION
**Pull request by shashd**
Co-authored-by: dannemarre

## PR Checklist:

[x] All new features have been tested
[x] All new features have been documented
[x] I have read the CONTRIBUTING.md file
[x] I will abide by the code of conduct

### CODE REVIEW

**Review by yuch3628 — CHANGES_REQUESTED** [review]
The code looks good. But we think you can test negative number,strings,or other types.

**Comment by shashd** [comment]
As for math.sqrt function, it requires the input to be float, int, or bool, otherwise, it will definitely throw an exception. And it doesn't support an negative number as input. So if I test these, the test won't pass.

**Comment by AntonBergaker** [comment]
We see that you use try - except inside the tests with print statements, which means that the exceptions will be printed and therefore tested.
The exceptions thrown should be the same as normal python does and can therefore pass. 

For example, you can see this in the test
"test_invalid_argument" here: https://github.com/shashd/voc_mp_group3/blob/master/tests/stdlib/test_collections.py#L134
Passing an int list to OrderedDict is an invalid type for OrderedDict, which expects a list of tuples. The test here makes sure that the java code and the python code throws the same type of error.

**Review by AntonBergaker — APPROVED** [review]
All tests pass and it tests what @yuch3628 mentioned. Good work.

**Review by yuch3628 — APPROVED** [review]

**Pull request merged**
