### PR TITLE
Implements ceil from math module

### PR DESCRIPTION
**Pull request by gustavborestam**
- [x] written and ran tests for new features
- [x] run code style check

### CODE REVIEW

**Comment by shashd** [comment]
I think you can also test Bool, it will output normally. And maybe you can combine some tests together, like test_ceil_float and test_ceil_neg_float? Because they are both floats.

**Review by dannemarre — COMMENTED** [review]
Why is the python/types/Int.java file changed with the public Int method?

**Comment by gustavborestam** [comment]
In python math.ceil() returns an int. Java's Math.ceil() function however, returns a double. We needed a way to instantiate an Int object with a double so we created it in Int.java

**Comment by shashd** [comment]
It makes sense. But when I paste your code and compile the jar file again on my computer. It fails and shows the error like this:
Error: Incompatible types: There may be losses when converting from double to long.

**Comment by gustavborestam** [comment]
I don't get that error when I compile and run it. Do you get this error when you compile the branch? Or are you only trying to compile parts of it? If so, what parts specifically did you try to compile that gave you the error?

**Comment by shashd** [comment]
I just copied all your code in my local VOC, and the error shows in math.java. But when I switch to origin/ceil branch, it compiles normally. I am not sure what causes this, but your code definitely works great.

**Review by shashd — APPROVED** [review]

**Review by dannemarre — APPROVED** [review]

**Pull request merged**
