### PR TITLE
🧮 Implements fabs from math module

### PR DESCRIPTION
**Pull request by AntonBergaker**
Adds fabs from the math module

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by avinkadir — CHANGES_REQUESTED** [review]
Math.java:
Are lines 8-19 needed if none of the objects are used in the code? On line 33, shouldn’t the function return the same type as the argument? We saw that the tests still passed but it didn’t make sense to us. Also, the variable castedNumber should be snake_case according to the coding convention. 

Otherwise we think you have done a great job!

**Comment by AntonBergaker** [comment]
Lines 8-19 are present in the other libraries in the code, we believe it's good to have them because in normal python you can type for example `math.__name__`. If you believe that's outside the scope of the PR we can remove them.

Line 33 matches how python behaves, `print(type(math.fabs(int(1))))`, but we agree it's not obvious so we added a comment to explain it better.

Good catch on the snake_case

**Review by gustavborestam — APPROVED** [review]
- Good updates that make it a lot clearer that fabs always returns a float. 
- Your justification for keeping lines 8-18 seem reasonable

Good job!

**Review by avinkadir — APPROVED** [review]
I agree with Gustav, thank you for the clarifications!

**Pull request merged**
